### ISSUE TITLE
how to use spark-shell use in library?

### ISSUE THREAD

**Issue by LeeByungwoo** [ravi72munde/spark-dynamo-stream-asl#2]
I am looking at the readme and following it, but it is not working. Can you help me? 😢 @ravi72munde 

i use this command and run readme sample code

`spark-shell --jars spark-streaming-dynambodb-kinesis-asl_2.11-2.4.0.jar --packages org.apache.spark:spark-streaming-kinesis-asl_2.11:2.4.0,com.amazonaws:dynamodb-streams-kinesis-adapter:1.4.0`

**Comment by ravi72munde** [comment]
Hey, I am not really familiar with usage through spark shell. I have always done this within Java/Scala project. If possible can you paste the errors and code snippet you are using?

**Comment by LeeByungwoo** [comment]
Thanks for the answer! i using reademe sampe code in spark shell . For me the error is that rdd is not printed.

**Comment by rbabu7** [comment]
Hi,
 Do you have  working pyspark code that reads data from Dynamodb Streams. Any help much appreciated

**Comment by LeeByungwoo** [comment]
The issue is old, so I'm closing it. thank you for the reply.
